#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED, then hacked up directly!
 * try not to overwrite it thanks
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_5x6_right(
	QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6,       KC_7, KC_8, KC_9, KC_0, KC_BSPC, 
	KC_TAB, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y,      KC_F, KC_G, KC_C, KC_R, KC_L, KC_SLSH, 
	KC_LSFT, KC_A, KC_O, KC_E, KC_U, KC_I,             KC_D, KC_H, KC_T, KC_N, KC_S, KC_MINS, 
	KC_LCTL, KC_SCLN, KC_Q, KC_J, KC_K, KC_X,          KC_B, KC_M, KC_W, KC_V, KC_Z, KC_BSLS, 
	             TO(2), TO(1),                         KC_BTN1, KC_BTN2, 
				 MO(2), KC_SPC,                        KC_ENT, //MO(1), 
				 KC_HOME, KC_END,                      KC_ENT, 
				 KC_BSPC, KC_LALT,                     KC_LGUI, KC_DEL
	),
	[1] = LAYOUT_5x6_right(
	KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,        KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TRNS, 
	KC_TRNS, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_LBRC,     KC_RBRC, KC_P7, KC_P8, KC_P9, KC_TRNS, KC_PLUS,
	KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_LPRN,      KC_RPRN, KC_P4, KC_P5, KC_P6, KC_EQL, KC_TRNS, 
	KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_P1, KC_P2, KC_P3, KC_MINS, KC_TRNS, 
	KC_TRNS, KC_TRNS,    KC_P0, KC_PDOT, 
	KC_TRNS, KC_TRNS,    KC_TRNS, 
	KC_TRNS, KC_TRNS,    KC_TRNS, 
	KC_TRNS, KC_TRNS,    KC_WAKE, KC_TRNS
	),
	[2] = LAYOUT_5x6_right(
	KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,              KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, 
	KC_TRNS, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_LBRC,    KC_RBRC, KC_TRNS, KC_INS, KC_VOLU, KC_VOLD, KC_MUTE, 
	KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_LPRN,     SNIPING, KC_BTN1, KC_BTN2, KC_BTN3, KC_BTN4, KC_BTN5, 
	KC_TRNS, KC_WH_L, KC_WH_U, KC_WH_D, KC_WH_R, DRGSCRL,   DPI_MOD, DPI_RMOD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
	KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, 
	KC_TRNS, KC_TRNS,    KC_TRNS, 
	KC_TRNS, KC_TRNS,    KC_TRNS, 
	KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS
	)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
